<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * Branch Model
 *
 * Representa una sucursal (salón de belleza) en la plataforma
 * Multi-tenant: Cada sucursal es administrada por un usuario admin
 *
 * @property int $id
 * @property int $admin_id
 * @property int|null $plan_id
 * @property string $name
 * @property string $slug
 * @property string|null $description
 * @property string|null $phone
 * @property string|null $whatsapp
 * @property string|null $email
 * @property string|null $address
 * @property float|null $latitude
 * @property float|null $longitude
 * @property string|null $logo
 * @property array|null $photos
 * @property array|null $hours
 * @property array|null $closed_days
 * @property string $timezone
 * @property string $country
 * @property string $currency
 * @property array|null $supported_languages
 * @property string $status
 * @property float $average_rating
 * @property int $total_reviews
 * @property bool $verified
 * @property \Carbon\Carbon|null $approved_at
 * @property \Carbon\Carbon|null $suspended_at
 * @property string|null $suspension_reason
 * @property array|null $settings
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 */
class Branch extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'branches';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<string>
     */
    protected $fillable = [
        'admin_id',
        'plan_id',
        'name',
        'slug',
        'description',
        'phone',
        'whatsapp',
        'email',
        'address',
        'latitude',
        'longitude',
        'logo',
        'photos',
        'hours',
        'closed_days',
        'timezone',
        'country',
        'currency',
        'supported_languages',
        'status',
        'average_rating',
        'total_reviews',
        'verified',
        'approved_at',
        'suspended_at',
        'suspension_reason',
        'settings',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'latitude' => 'decimal:8',
        'longitude' => 'decimal:8',
        'photos' => 'array',
        'hours' => 'array',
        'closed_days' => 'array',
        'supported_languages' => 'array',
        'average_rating' => 'decimal:2',
        'total_reviews' => 'integer',
        'verified' => 'boolean',
        'approved_at' => 'datetime',
        'suspended_at' => 'datetime',
        'settings' => 'array',
    ];

    /**
     * Branch statuses
     */
    public const STATUS_PENDING = 'pending';
    public const STATUS_APPROVED = 'approved';
    public const STATUS_SUSPENDED = 'suspended';

    /**
     * Get the admin user of this branch.
     *
     * @return BelongsTo
     */
    public function admin(): BelongsTo
    {
        return $this->belongsTo(User::class, 'admin_id');
    }

    /**
     * Get all stylists working at this branch.
     *
     * @return HasMany
     */
    public function stylists(): HasMany
    {
        return $this->hasMany(Stylist::class);
    }

    /**
     * Get all services offered by this branch.
     *
     * @return HasMany
     */
    public function services(): HasMany
    {
        return $this->hasMany(Service::class);
    }

    /**
     * Get all payments processed by this branch.
     *
     * @return HasMany
     */
    public function payments(): HasMany
    {
        return $this->hasMany(Payment::class);
    }

    /**
     * Get all invoices generated by this branch.
     *
     * @return HasMany
     */
    public function invoices(): HasMany
    {
        return $this->hasMany(Invoice::class);
    }

    /**
     * Check if branch is active
     *
     * @return bool
     */
    public function isActive(): bool
    {
        return $this->status === self::STATUS_APPROVED;
    }

    /**
     * Check if branch is verified
     *
     * @return bool
     */
    public function isVerified(): bool
    {
        return $this->verified === true;
    }

    /**
     * Check if branch is suspended
     *
     * @return bool
     */
    public function isSuspended(): bool
    {
        return $this->status === self::STATUS_SUSPENDED;
    }

    /**
     * Suspend this branch
     *
     * @param string $reason
     * @return bool
     */
    public function suspend(string $reason): bool
    {
        $this->status = self::STATUS_SUSPENDED;
        $this->suspended_at = now();
        $this->suspension_reason = $reason;
        return $this->save();
    }

    /**
     * Approve this branch
     *
     * @return bool
     */
    public function approve(): bool
    {
        $this->status = self::STATUS_APPROVED;
        $this->approved_at = now();
        return $this->save();
    }
}
